export const defaultFormValues = {
  directorId: '',
  emailAddress: '',
  firstName: '',
  lastName: '',
  mobileNumber: '',
  idType: '',
  idNumber: '',
  expiryDate: '',
  placeOfIssue: '',
  position: '',
  stakeHolderType: '',
  frontImage: '',
  backImage: '',
  portraitImage: '',
}
