export const defaultFormValues = {
  type: 'new',
  // fullname: '',
  // emailaddress: '',
  // membertype: '',
  // userrole: '',
  // status: '',
  // createdbyupdatedbymail: '',

    emailAddress: "",
    firstName: "",
    lastName: "",
    mobileNumber: "",
    idType: "Select an option",
    idNumber: "",
    expiryDate: "",
    placeOfIssue: "",
    position: "Select an option",
    stakeHolderType: "Select an option",
    frontImage: "",
    backImage: "",
    portraitImage : "",
}
